name: Read the content of files that were updated in the PR

#on:
#  pull_request:
#    branches:
#      - master
on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get changed files
        id: get_files
        env:
          FILES_CHANGED: $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) 
        run: |
          echo "Files changed: $FILES_CHANGED"         
        shell: bash

      - name: Run pr changed files script
        run: |
          files=$(echo "${FILES_CHANGED}" | tr '\n' ' ')
          ./print-pr-files-changed-full.py $files
        shell: bash
