name: Read the content of files that were updated in the PR

#on:
#  pull_request:
#    branches:
#      - master
on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get changed files
        id: get_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
        shell: bash

      - name: Run pr changed files script
        run: |
          files=$(echo "${{ steps.get_files.outputs.files }}" | tr '\n' ' ')
          ./validate-code.py $files
        shell: bash
